---
title: "Susana Roman Garcia"
---
I am an advocate for open, reproducible, and ethical science. My focus is on fostering interdisciplinary collaboration and discussions about ethics, reproducibility, and data hazards.

```{=html}
  <div class="content">

    <div class="row">

        <div id="title" style="margin-top: 1rem;">

          <div style="font-size: 1em;"><a href="resources/SusanaRG_CV.pdf">CV</a> · <a
              href="https://github.com/Susana465">GitHub</a> · <a
              href="https://www.linkedin.com/in/susana-roman-garcia/">LinkedIn</a></div>

        </div>
      </div>

```

## About me

I am a [PhD student ](projects.qmd#sec-phd) at the University of Edinburgh, funded by Medical Research Scotland. I am interested in learning about Open Science, Ethics, Computer Science, and Neuroscience, and how to mix them all-together. Outside of work and academia you can find me growing vegetables, petting cats, or at the pub next door with a good book. 

I also very much care about the environment (not as separate from humans), and the intersectional impacts of the current climate crisis. I see all parts of my life as inter-connected, not as isolated sections. I work and live to create a new vision of what the world can be.

## About my work

I started my PhD in order to better understand how memory works inside our brains. In order to do so, I look at the molecular mechanisms of memory and create computer models of their interactions that can help predict how molecules are working inside neurons.

I think that in order to create meaningful research, it must challenge the imperialist white supermacist patriarchal culture it sits in. I believe there is a need to move away from historically white, cis-male, centered science, to a science that is much more inclusive and accessible to everyone and especially those who have been historically marginalized.

Reproducibility and bias in science are huge driving forces of how I work. Making reproducible science means a bit more time is needed at the beginning, but in the long run money, time and resources are saved by not repeating the same research over and over again. Similarly, I see no point in creating amazingly reproducible research, if this is carrying sexist, racist, ableist, speciesist or any kind of oppressive bias that continues to disproportionately affect some individuals more than others.

These are resons why I combine Ethics with Neuroscience and Computer Science in my work. To create computer models of molecular interactions that are reproducible, and that take into account real-world repercussions.

### I am currently...

-  Finishing my PhD <p>&#x1F4AA;</p>
-  Looking for jobs<p>&#128064;</p>
-  Growing fruit and vegetables in the garden<p>&#127804;</p>
