---
title: "Talks and Publications"
---
##### **Welsh C., Román García S., Barnett G.C., Jena, R., (2024). Democratising artificial intelligence in healthcare: community-driven approaches for ethical solutions. [https://doi.org/10.1016/j.fhj.2024.100165](https://doi.org/10.1016/j.fhj.2024.100165)**

Abstract: The rapid advancement and widespread adoption of artificial intelligence (AI) has ushered in a new era of possibilities in healthcare, ranging from clinical task automation to disease detection. AI algorithms have the potential to analyse medical data, enhance diagnostic accuracy, personalise treatment plans and predict patient outcomes among other possibilities. With a surge in AI's popularity, its developments are outpacing policy and regulatory frameworks, leading to concerns about ethical considerations and collaborative development. Healthcare faces its own ethical challenges, including biased datasets, under-representation and inequitable access to resources, all contributing to mistrust in medical systems. To address these issues in the context of AI healthcare solutions and prevent perpetuating existing inequities, it is crucial to involve communities and stakeholders in the AI lifecycle. This article discusses four community-driven approaches for co-developing ethical AI healthcare solutions, including understanding and prioritising needs, defining a shared language, promoting mutual learning and co-creation, and democratising AI. These approaches emphasise bottom-up decision-making to reflect and centre impacted communities' needs and values. These collaborative approaches provide actionable considerations for creating equitable AI solutions in healthcare, fostering a more just and effective healthcare system that serves patient and community needs.

##### **Roman Garcia, S., Welsh, C., Di Cara, N. H., Sterratt, D., Romano, N., & Stefan, M. I. (2024). Data Hazards as an ethical toolkit for neuroscience. [https://doi.org/10.31219/osf.io/yn2j9_](https://doi.org/10.31219/osf.io/yn2j9)**

Abstract: The Data Hazards framework (Zelenkaet al., 2024) is intended to encouragethinking about the ethical implications of data science projects. It takes the formof community-designed data hazard labels, similar to warning labels on chemicals,that can encourage reflection and discussion on what ethical risks are associatedwith a project and how they can be mitigated. In this article, we explain howthe Data Hazards framework can apply to neuroscience. We demonstrate howthe hazards can be applied to one of our own projects, on the computationalmodelling of postsynaptic mechanisms.

##### **Roman Garcia, & Steele. (2023). Open Science & Reproducibility: The Turing Way Workshop. [https://doi.org/10.5281/zenodo.7704563](https://doi.org/10.5281/zenodo.7704563)**

Presented at Newcastle University's conference from 6-7 March 2023: "Data Science Perspectives - Multidisciplinary PhD Conference".

##### **Kuwertz E., Zelenka N., Hanschke V., Di Cara N., Bennet E., Kherroubi Garcia I., Roman Garcia, S., (2023).  Data Hazards v1.0: an open-source vocabulary of ethical hazards for data-intensive projects. [https://doi.org/10.31219/osf.io/hzmyp](https://doi.org/10.31219/osf.io/hzmyp)**

Description: This paper presents the Data Hazards project, which contains a shared, controlled vocabulary of 11 data. Similarly to chemical hazard labels, the Data Hazards serve as a warning of a potential risk, and encourage; description: The labels were co-created as an open-source project, where they will continue to evolve over time with; description: : a mismatched vocabulary and a lack of an accessible structure for discussions.; title: Data Hazards v1.0: an open-source vocabulary of ethical hazards for data-intensive projects; description: The use of data-intensive methods for tasks which impact peoples’ lives continues to accelerate.

##### **Roman Garcia, S., (2023) Ethical Standards and Reproducibility of computer models in Neurobiology, Open Life Sciences.**

You can watch the [recorded live session](https://www.youtube.com/watch?v=3qb28JDFhGw), where me and other OLS-6 participants present the projects we worked on during our time at OLS.

##### **Roman Garcia, S. (2023). Enrichment scheme reflections. Women in High Performance Computing.**

I was invited by Women in High Performance Computing to write a guest blog post on my experience as an enrichmment student, which you can find [in their website here](https://womeninhpc.org/paths-to-hpc/enrichment-scheme-reflections-the-alan-turing-institute).

##### **Roman Garcia, S., Sterratt, D., & Stefan, M. I.(2022).  Thinking about Ethics in (Computer) Science, Edinburgh College of Medicine and Veterinary Medicine Good Practice Showcase. [https://doi.org/10.5281/zenodo.6973796](https://doi.org/10.5281/zenodo.6973796)**

You can watch the recording [here](https://youtu.be/8wAfcTM_ypA), and access slides [here](https://zenodo.org/record/6973796#.YvDqOHbMKUk).

<iframe width="550" height="380" src="https://www.youtube.com/embed/8wAfcTM_ypA" title="Thinking about Ethics in (Computer) Science" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
